### ISSUE TITLE
[Possible Critical BUG] Possible Critical Bug in tmc4671_doEncoderInitializationMode2 (TMC-API/tmc/ic/TMC4671/TMC4671.c)

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-EvalSystem#21]
The code block "if(hall_phi_e_old != hall_phi_e_new)" is not always executed in the function tmc4671_doEncoderInitializationMode2 (initialization by combining of hall sensors and encoder). 

When we start the function tmc4671_doEncoderInitializationMode2(...), the executing flow is firstly getting into "case STATE_START_INIT:". In this case, we could get the hall_phi_e_old value through the following line:
// read actual hall angle
hall_phi_e_old = (int16_t) tmc4671_readRegister16BitValue(motor, TMC4671_HALL_PHI_E_INTERPOLATED_PHI_E, BIT_0_TO_15);

The executing flow is then getting into "case STATE_WAIT_INIT_TIME:". We could then get the hall_phi_e_new value through the following line:
// read actual hall angle
hall_phi_e_new = (int16_t) tmc4671_readRegister16BitValue(motor, TMC4671_HALL_PHI_E_INTERPOLATED_PHI_E, BIT_0_TO_15);

The problem is that, the code block "if(hall_phi_e_old != hall_phi_e_new)" is not always executed. It may depend on the motor's current position. Say, after we successfully executed the function tmc4671_doEncoderInitializationMode2(...) and finished the encoder initialization by combining of hall sensors and encoder, the next time, when we restart the system (the motor keep the current position when restart the system) and excute the function tmc4671_doEncoderInitializationMode2(...), the code block "if(hall_phi_e_old != hall_phi_e_new)" cannot be executed during the initialization process except we manually move the motor position a little bit. We expect that the code block "if(hall_phi_e_old != hall_phi_e_new)" is always executed when we executed the initialization by hall sensors and encoder.

**[Possible explanation]** When the motor's current position is in the appropriate position, the motor may not have to rotate for the initialization process. We think that the code in the function tmc4671_doEncoderInitializationMode2(...) should deal with the case in the "case STATE_WAIT_INIT_TIME:" part.

**Comment by huskier** [comment]
@trinamic-LH Hi, Lenard, could you please help on this issue?

**Comment by trinamic-LH** [comment]
Hi,

I forwarded this issue to a colleague who will get back to you.

Regards,
Lenard

**Comment by trinamic** [comment]
Hi Huskier,

yes you are right. There was a line missing to use the hall signals for startup during initialization (to generate force on the motor). Please have a look to this line: https://github.com/trinamic/TMC-API/blob/64295eec684a1f59d4085828854487650e9c9f2e/tmc/ic/TMC4671/TMC4671.c#L390

If you are using the wizard in the IDE then the wizard moves the motor in open loop mode, thus the motor was moved by a force. Without the wizard the motor is typically in stand still and the check:

// wait until hall angle changed
if (hall_phi_e_old != hall_phi_e_new) 
{...}

was not triggered.

Thanks for this hint, should be fixed now. (Tested with wizard in the TMCL-IDE and the attached TPC script.)
[TMC4671-EVAL_Settings.tpc.txt](https://github.com/trinamic/TMC-EvalSystem/files/6587867/TMC4671-EVAL_Settings.tpc.txt)

(the ".txt" at the end of the filename must be removed, to use it in the TMCL-IDE)

Regards,
Enrico

**Comment by huskier** [comment]
@trinamic Thank you for your effort, Enrico. However, the problem is still there, the code block "if(hall_phi_e_old != hall_phi_e_new)" is not always executed. It may depend on the motor's current position. Say, after we successfully executed the function tmc4671_doEncoderInitializationMode2(...) and finished the encoder initialization by combining of hall sensors and encoder, the next time, when we restart the system (the motor keep the current position when restart the system) and execute the function tmc4671_doEncoderInitializationMode2(...), the code block "if(hall_phi_e_old != hall_phi_e_new)" cannot be executed during the initialization process except we manually move the motor position a little bit. We expect that the code block "if(hall_phi_e_old != hall_phi_e_new)" is always executed when we executed the initialization by hall sensors and encoder.

We guess when the motor's current position is in the appropriate position, the motor may not have to rotate for the initialization process. 

At present, we add an "ELSE block" to deal with this issue. After waiting a while for initialization, if the hall_phi_e_new is still equal hall_phi_e_old, then we think the initialization has completed.

```
		// wait until hall angle changed
		if(*hall_phi_e_old != *hall_phi_e_new)
		{
			// estimated value = old value + diff between old and new (handle int16_t overrun)
			int16_t hall_phi_e_estimated = *hall_phi_e_old + tmc4671_getS16CircleDifference(*hall_phi_e_new, *hall_phi_e_old)/2;

			// read actual abn_decoder angle and consider last set abn_decoder_offset
			int16_t abn_phi_e_actual = (int16_t) tmc4671_readRegister16BitValue(motor, TMC4671_ABN_DECODER_PHI_E_PHI_M, BIT_16_TO_31) - *hall_actual_coarse_offset;

			// set ABN_DECODER_PHI_E_OFFSET to actual estimated angle - abn_phi_e_actual difference
			tmc4671_writeRegister16BitValue(motor, TMC4671_ABN_DECODER_PHI_E_PHI_M_OFFSET, BIT_16_TO_31, tmc4671_getS16CircleDifference(hall_phi_e_estimated, abn_phi_e_actual));

			// switch back to last used PHI_E_SELECTION setting
			tmc4671_writeRegister16BitValue(motor, TMC4671_PHI_E_SELECTION, BIT_0_TO_15, *last_Phi_E_Selection);

			// go to ready state
			*initState = 0;

			dispString("[Mode2] In if(hall_phi_e_old != hall_phi_e_new)......");
		}
		else
		{
			// go to ready state
			SumTimeTemp += 1;
			if(SumTimeTemp == 10000)
			{
				*initState = 0;
				SumTimeTemp = 0;
				dispString("[Mode2] In if(hall_phi_e_old == hall_phi_e_new).......");
			}

		}
		break;
```

**Comment by trinamic** [comment]
Hi,

tmc4671_writeRegister16BitValue(motor, TMC4671_PHI_E_SELECTION, BIT_0_TO_15, TMC4671_PHI_E_HALL); in the STATE_START_INIT state selects the use of the hall sensor signal for motor commutation. Then with

if(*hall_phi_e_old != *hall_phi_e_new)

the state machine is waiting for a hall sensor change. This change is necessary for a good encoder alignment with the hall sensors. This change can only be made with a minimal motor movement, thus you need some torque on the motor. 

In the script I set the PHI_E_Selection to use the ABN-Encoder (thus, it is used at the end of the initialization automatically)

WMC PHI_E_SELECTION, 0, $00000003, 1

Then I trigger the encoder init with:     SAP 252, 0, 2, 1
to start the state machine and let the state-machine wait for the hall-sensor-change. And then I apply the needed torque to turn the motor and force the hall-sensor change. (This can be made with torque or velocity mode). Thus the encoder init is done within the first movement automatically.

Regards,
    Enrico
